export const TIMEZONES = [
  { value: "UTC", label: "UTC (Coordinated Universal Time)" },
  { value: "Europe/London", label: "Europe/London (GMT)" },
  { value: "Europe/Paris", label: "Europe/Paris (CET)" },
  { value: "Europe/Berlin", label: "Europe/Berlin (CET)" },
  { value: "Europe/Madrid", label: "Europe/Madrid (CET)" },
  { value: "Europe/Rome", label: "Europe/Rome (CET)" },
  { value: "Europe/Amsterdam", label: "Europe/Amsterdam (CET)" },
  { value: "Europe/Brussels", label: "Europe/Brussels (CET)" },
  { value: "Europe/Vienna", label: "Europe/Vienna (CET)" },
  { value: "Europe/Stockholm", label: "Europe/Stockholm (CET)" },
  { value: "Europe/Oslo", label: "Europe/Oslo (CET)" },
  { value: "Europe/Copenhagen", label: "Europe/Copenhagen (CET)" },
  { value: "Europe/Helsinki", label: "Europe/Helsinki (EET)" },
  { value: "Europe/Athens", label: "Europe/Athens (EET)" },
  { value: "Europe/Istanbul", label: "Europe/Istanbul (TRT)" },
  { value: "Europe/Moscow", label: "Europe/Moscow (MSK)" },
  { value: "America/New_York", label: "America/New York (EST)" },
  { value: "America/Chicago", label: "America/Chicago (CST)" },
  { value: "America/Denver", label: "America/Denver (MST)" },
  { value: "America/Los_Angeles", label: "America/Los Angeles (PST)" },
  { value: "America/Phoenix", label: "America/Phoenix (MST)" },
  { value: "America/Toronto", label: "America/Toronto (EST)" },
  { value: "America/Vancouver", label: "America/Vancouver (PST)" },
  { value: "America/Montreal", label: "America/Montreal (EST)" },
  { value: "America/Mexico_City", label: "America/Mexico City (CST)" },
  { value: "America/Bogota", label: "America/Bogota (COT)" },
  { value: "America/Lima", label: "America/Lima (PET)" },
  { value: "America/Buenos_Aires", label: "America/Buenos Aires (ART)" },
  { value: "America/Sao_Paulo", label: "America/São Paulo (BRT)" },
  { value: "America/Santiago", label: "America/Santiago (CLT)" },
  { value: "America/Caracas", label: "America/Caracas (VET)" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo (JST)" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai (CST)" },
  { value: "Asia/Hong_Kong", label: "Asia/Hong Kong (HKT)" },
  { value: "Asia/Singapore", label: "Asia/Singapore (SGT)" },
  { value: "Asia/Seoul", label: "Asia/Seoul (KST)" },
  { value: "Asia/Bangkok", label: "Asia/Bangkok (ICT)" },
  { value: "Asia/Jakarta", label: "Asia/Jakarta (WIB)" },
  { value: "Asia/Manila", label: "Asia/Manila (PHT)" },
  { value: "Asia/Taipei", label: "Asia/Taipei (CST)" },
  { value: "Asia/Kuala_Lumpur", label: "Asia/Kuala Lumpur (MYT)" },
  { value: "Asia/Ho_Chi_Minh", label: "Asia/Ho Chi Minh (ICT)" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata (IST)" },
  { value: "Asia/Mumbai", label: "Asia/Mumbai (IST)" },
  { value: "Asia/Dubai", label: "Asia/Dubai (GST)" },
  { value: "Asia/Tel_Aviv", label: "Asia/Tel Aviv (IST)" },
  { value: "Asia/Jerusalem", label: "Asia/Jerusalem (IST)" },
  { value: "Asia/Riyadh", label: "Asia/Riyadh (AST)" },
  { value: "Asia/Karachi", label: "Asia/Karachi (PKT)" },
  { value: "Asia/Dhaka", label: "Asia/Dhaka (BST)" },
  { value: "Australia/Sydney", label: "Australia/Sydney (AEDT)" },
  { value: "Australia/Melbourne", label: "Australia/Melbourne (AEDT)" },
  { value: "Australia/Brisbane", label: "Australia/Brisbane (AEST)" },
  { value: "Australia/Perth", label: "Australia/Perth (AWST)" },
  { value: "Australia/Adelaide", label: "Australia/Adelaide (ACDT)" },
  { value: "Pacific/Auckland", label: "Pacific/Auckland (NZDT)" },
  { value: "Pacific/Fiji", label: "Pacific/Fiji (FJT)" },
  { value: "Pacific/Honolulu", label: "Pacific/Honolulu (HST)" },
  { value: "Africa/Cairo", label: "Africa/Cairo (EET)" },
  { value: "Africa/Johannesburg", label: "Africa/Johannesburg (SAST)" },
  { value: "Africa/Lagos", label: "Africa/Lagos (WAT)" },
  { value: "Africa/Nairobi", label: "Africa/Nairobi (EAT)" },
  { value: "Africa/Casablanca", label: "Africa/Casablanca (WET)" },
];